name: Build Upsync Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish Upsync
        run: |
          dotnet publish -p:PublishSingleFile=true --self-contained -c Release src/tools/upsync/upsync.csproj
          
      - name: Copy MicRooCerAut2011_2011_03_22
        run: |       
          echo "-----BEGIN CERTIFICATE-----" > out/upsync/Release/net9.0/linux-x64/publish/MicRooCerAut2011_2011_03_22.crt && curl -s https://www.microsoft.com/pki/certs/MicRooCerAut2011_2011_03_22.crt | openssl base64 >> out/upsync/Release/net9.0/linux-x64/publish/MicRooCerAut2011_2011_03_22.crt && echo "-----END CERTIFICATE-----" >> out/upsync/Release/net9.0/linux-x64/publish/MicRooCerAut2011_2011_03_22.crt
          
      - name: Create requirement.sh
        run: |
          echo "sudo apt-get install -y cabextract && cp MicRooCerAut2011_2011_03_22.crt /usr/local/share/ca-certificates/MicRooCerAut2011_2011_03_22.crt && sudo update-ca-certificates" > out/upsync/Release/net9.0/linux-x64/publish/requirement.sh

      - name: Create ZIP of the artifact
        run: |
          zip -jr out/upsync-linux.zip out/upsync/Release/net9.0/linux-x64/publish/*

      - name: Upload build logs to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux-${{ github.sha }}
          files: out/upsync-linux.zip